Repository redBorder/rb-logstatter, pull requests merged in 2023-12, with the labels that each got.

#2 Add auto bumping
  .github/workflows/buldrpm.yml
Labels: size/L, kind/feature

#3 Update README
  README.md
Labels: kind/documentation, size/XS

#5 Fix auto bumping
  .github/workflows/buldrpm.yml
Labels: kind/bug, size/XS

#7 Fix workflows
  .github/workflows/buldrpm.yml
Labels: kind/bug, size/M

#8 Release/0.0.2
  .github/workflows/buldrpm.yml
  README.md
  packaging/rpm/rb-logstatter.spec
Labels: size/L, kind/documentation

#9 Release 0.0.1
  packaging/rpm/rb-logstatter.spec
Labels: kind/documentation, size/XS
